# Generated by Django 5.0.6 on 2024-05-22 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Harajat Kategoriyasi',
                'verbose_name_plural': 'Harajat Kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tavsif')),
                ('date', models.DateField(verbose_name='Sana')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.account', verbose_name='Hisob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense_app.expensecategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Harajat',
                'verbose_name_plural': 'Harajatlar',
            },
        ),
    ]
